### ISSUE TITLE
Error: can't find file 'log'

### ISSUE THREAD

**Issue by leahpleurodon** [mamantoha/crest#141]
Hello there here is the following issue I get when trying to run my specs:

```
In lib/crest/src/crest/logger.cr:1:1

 1 | require "log"
     ^
Error: can't find file 'log'
```

**Comment by mamantoha** [comment]
Hi @leahpleurodon 
Please make sure you are using Crystal >= 0.34.0.
Probably you are using old version of Crystal.

**Comment by leahpleurodon** [comment]
Correct you are!

thanks!
