### ISSUE TITLE
Repeating request on failure

### ISSUE THREAD

**Issue by marcstein** [mamantoha/crest#202]
The application that I'm working on submits an authentication request and receives a token and then uses that token to submit a request for data. Sometimes, the auth succeeds but the main request times out. I want to trigger a repeat of the main request at that point.

I can catch the error and repeat the request, but that seems to cause an issue with the subsequent processes. Is there a recommended way to repeat on failure?

Thanks!
Marc

**Comment by mamantoha** [comment]
Hi @marcstein .

I don't have recommended method of how to re-run a request if a timeout error occurs.

But you can use my solution which is used in one of my [projects](https://github.com/mamantoha/shards-info/blob/master/src/lib/gitlab/api.cr#L49-L55): 

```crystal
def make_request(url : String, params = {} of String => String)
  Retriable.retry(on: {Crest::InternalServerError, Crest::ServiceUnavailable}) do
    client[url].get(params: params)
  end
ensure
  client.http_client.close
end
```

It is used [retriable.cr](https://github.com/Sija/retriable.cr) shard.
