### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by psikoz** [mamantoha/crest#91]
Hi @mamantoha I want to design a logo for crest. If there is your an idea, please tell me.

**Comment by mamantoha** [comment]
Hi @psikoz.

I'm happy to accept any help. As you may notice `crest` already has a simple logo.
One thing you should know about the name is `[Cr]ystal + [REST] = crest`

**Comment by mamantoha** [comment]
Thanks a lot @psikoz

I like the last one. Could you please add a lowercase name.

**Comment by psikoz** [comment]
You are welcome but I do not fully understand. Which one do you prefer?

![crest](https://user-images.githubusercontent.com/40601249/42322629-e56bcaf0-8065-11e8-80d4-ab5e7b808b2d.jpg)

**Comment by mamantoha** [comment]
The first one :+1: . Please make text `crest` and it good to PR.

**Comment by psikoz** [comment]
I sent a pull-request. I hope there is no problem.
